version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TopSecret123!
    ports:
      - '5432:5432'
    command: >
      sh -c "sleep 5 && ./dbpop/popDB.go"